name: flutter_tex_example
description: A Flutter Package (Demo) to render LaTeX with full HTML and JavaScript support.
homepage: https://github.com/shahxadakram/flutter_tex

version: 3.6.12+22

publish_to: "none"

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tex:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/mathjax_config.js
    - assets/flutter_tex.css
